function tableout = importfile(workbookFile,nan_values)
%IMPORTFILE Import data from a spreadsheet
%   DATA = IMPORTFILE(FILE) reads data from the first worksheet in the
%   Microsoft Excel spreadsheet file named FILE and returns the data as a
%   table.
%
%   DATA = IMPORTFILE(FILE,SHEET) reads from the specified worksheet.
%
%   DATA = IMPORTFILE(FILE,SHEET,STARTROW,ENDROW) reads from the specified
%   worksheet for the specified row interval(s). Specify STARTROW and
%   ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.
%
%	Non-numeric cells are replaced with: NaN
%
% Example:
%   pp10trial1 = importfile('pp10_trial1.xls','Sheet1',2,266);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2018/08/25 08:46:09

%% Input handling

% If no sheet is specified, read first sheet
% if nargin == 1 || isempty(sheetName)
%     sheetName = 1;
% end

%% Import the data
[~, ~, raw] = xlsread(workbookFile, 1);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
if nan_values == 0
    raw(R) = {0.0}; % Replace non-numeric cells
else
    raw(R) = {NaN};
end

%% Create output variable
I = cellfun(@(x) ischar(x), raw);
raw(I) = {NaN};
data = reshape([raw{:}],size(raw));

%% Create table
tableout = table;

%% Allocate imported array to column variable names
tableout.KinectxSpineBase = data(:,1);
tableout.KinectxHead = data(:,2);
tableout.KinectxShoulderLeft = data(:,3);
tableout.KinectxElbowLeft = data(:,4);
tableout.KinectxWristLeft = data(:,5);
tableout.KinectxHandLeft = data(:,6);
tableout.KinectxShoulderRight = data(:,7);
tableout.KinectxElbowRight = data(:,8);
tableout.KinectxWristRight = data(:,9);
tableout.KinectxHandRight = data(:,10);
tableout.KinectxHipLeft = data(:,11);
tableout.KinectxKneeLeft = data(:,12);
tableout.KinectxAnkleLeft = data(:,13);
tableout.KinectxFootLeft = data(:,14);
tableout.KinectxHipRight = data(:,15);
tableout.KinectxKneeRight = data(:,16);
tableout.KinectxAnkleRight = data(:,17);
tableout.KinectxFootRight = data(:,18);
tableout.KinectxSpineShoulder = data(:,19);
tableout.KinectySpineBase = data(:,20);
tableout.KinectyHead = data(:,21);
tableout.KinectyShoulderLeft = data(:,22);
tableout.KinectyElbowLeft = data(:,23);
tableout.KinectyWristLeft = data(:,24);
tableout.KinectyHandLeft = data(:,25);
tableout.KinectyShoulderRight = data(:,26);
tableout.KinectyElbowRight = data(:,27);
tableout.KinectyWristRight = data(:,28);
tableout.KinectyHandRight = data(:,29);
tableout.KinectyHipLeft = data(:,30);
tableout.KinectyKneeLeft = data(:,31);
tableout.KinectyAnkleLeft = data(:,32);
tableout.KinectyFootLeft = data(:,33);
tableout.KinectyHipRight = data(:,34);
tableout.KinectyKneeRight = data(:,35);
tableout.KinectyAnkleRight = data(:,36);
tableout.KinectyFootRight = data(:,37);
tableout.KinectySpineShoulder = data(:,38);
tableout.KinectzSpineBase = data(:,39);
tableout.KinectzHead = data(:,40);
tableout.KinectzShoulderLeft = data(:,41);
tableout.KinectzElbowLeft = data(:,42);
tableout.KinectzWristLeft = data(:,43);
tableout.KinectzHandLeft = data(:,44);
tableout.KinectzShoulderRight = data(:,45);
tableout.KinectzElbowRight = data(:,46);
tableout.KinectzWristRight = data(:,47);
tableout.KinectzHandRight = data(:,48);
tableout.KinectzHipLeft = data(:,49);
tableout.KinectzKneeLeft = data(:,50);
tableout.KinectzAnkleLeft = data(:,51);
tableout.KinectzFootLeft = data(:,52);
tableout.KinectzHipRight = data(:,53);
tableout.KinectzKneeRight = data(:,54);
tableout.KinectzAnkleRight = data(:,55);
tableout.KinectzFootRight = data(:,56);
tableout.KinectzSpineShoulder = data(:,57);
tableout.OptotrakxSpineBase = data(:,58);
tableout.OptotrakxHead = data(:,59);
tableout.OptotrakxShoulderLeft = data(:,60);
tableout.OptotrakxElbowLeft = data(:,61);
tableout.OptotrakxWristLeft = data(:,62);
tableout.OptotrakxHandLeft = data(:,63);
tableout.OptotrakxShoulderRight = data(:,64);
tableout.OptotrakxElbowRight = data(:,65);
tableout.OptotrakxWristRight = data(:,66);
tableout.OptotrakxHandRight = data(:,67);
tableout.OptotrakxHipLeft = data(:,68);
tableout.OptotrakxKneeLeft = data(:,69);
tableout.OptotrakxAnkleLeft = data(:,70);
tableout.OptotrakxFootLeft = data(:,71);
tableout.OptotrakxHipRight = data(:,72);
tableout.OptotrakxKneeRight = data(:,73);
tableout.OptotrakxAnkleRight = data(:,74);
tableout.OptotrakxFootRight = data(:,75);
tableout.OptotrakxSpineShoulder = data(:,76);
tableout.OptotrakySpineBase = data(:,77);
tableout.OptotrakyHead = data(:,78);
tableout.OptotrakyShoulderLeft = data(:,79);
tableout.OptotrakyElbowLeft = data(:,80);
tableout.OptotrakyWristLeft = data(:,81);
tableout.OptotrakyHandLeft = data(:,82);
tableout.OptotrakyShoulderRight = data(:,83);
tableout.OptotrakyElbowRight = data(:,84);
tableout.OptotrakyWristRight = data(:,85);
tableout.OptotrakyHandRight = data(:,86);
tableout.OptotrakyHipLeft = data(:,87);
tableout.OptotrakyKneeLeft = data(:,88);
tableout.OptotrakyAnkleLeft = data(:,89);
tableout.OptotrakyFootLeft = data(:,90);
tableout.OptotrakyHipRight = data(:,91);
tableout.OptotrakyKneeRight = data(:,92);
tableout.OptotrakyAnkleRight = data(:,93);
tableout.OptotrakyFootRight = data(:,94);
tableout.OptotrakySpineShoulder = data(:,95);
tableout.OptotrakzSpineBase = data(:,96);
tableout.OptotrakzHead = data(:,97);
tableout.OptotrakzShoulderLeft = data(:,98);
tableout.OptotrakzElbowLeft = data(:,99);
tableout.OptotrakzWristLeft = data(:,100);
tableout.OptotrakzHandLeft = data(:,101);
tableout.OptotrakzShoulderRight = data(:,102);
tableout.OptotrakzElbowRight = data(:,103);
tableout.OptotrakzWristRight = data(:,104);
tableout.OptotrakzHandRight = data(:,105);
tableout.OptotrakzHipLeft = data(:,106);
tableout.OptotrakzKneeLeft = data(:,107);
tableout.OptotrakzAnkleLeft = data(:,108);
tableout.OptotrakzFootLeft = data(:,109);
tableout.OptotrakzHipRight = data(:,110);
tableout.OptotrakzKneeRight = data(:,111);
tableout.OptotrakzAnkleRight = data(:,112);
tableout.OptotrakzFootRight = data(:,113);
tableout.OptotrakzSpineShoulder = data(:,114);

